### PR TITLE
C2C-333: Modified Lab Tests in OpenELIS

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket here: https://mekomsolutions.atlassian.net/browse/C2C-333

### CODE REVIEW

**Review by Ruhanga — COMMENTED** [review]
@kazlaw, are these changes about introducing new labs + changing of some existing ones?

**Comment by kazlaw** [comment]
> @kazlaw, are these changes about introducing new labs + changing of some existing ones?

Yes they are @Ruhanga

**Comment by Ruhanga** [comment]
> changing of some existing ones?

Chaning of names only and not datatypes, correct? @kazlaw

**Comment by kazlaw** [comment]
Yes

> > changing of some existing ones?
> 
> Changing of names, answers, only and not datatypes, correct? @kazlaw

Yes @Ruhanga

**Review by Ruhanga — APPROVED** [review]
LGTM

**Pull request merged**
