### PR TITLE
C2C-276: Updated concept from Gastritis to Gastritis crisis

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket here : https://mekomsolutions.atlassian.net/browse/C2C-276

This fixes the error that happens at C2C level because of the change of concept.

image

### CODE REVIEW

**Review by Ruhanga — CHANGES_REQUESTED** [review]
Thanks @kazlaw. Both `Gastritis` and `Gastritis crisis (K29.7)` should be apart of this concept set.

**Comment by kazlaw** [comment]
> Thanks @kazlaw. Both `Gastritis` and `Gastritis crisis (K29.7)` should be apart of this concept set.

@Ruhanga does this mean I should do it for all the other locations as well?

**Comment by Ruhanga** [comment]
> does this mean I should do it for all the other locations as well?

 What do you mean by locations @kazlaw?

**Comment by kazlaw** [comment]
> > does this mean I should do it for all the other locations as well?
> 
> What do you mean by locations @kazlaw?

There is a PR at the Haiti level @Ruhanga  --> https://github.com/mekomsolutions/openmrs-config-haiti/pull/157/files

**Comment by Ruhanga** [comment]
> https://github.com/mekomsolutions/openmrs-config-haiti/pull/157/files , by locations I meant in this PR.

Correct @kazlaw. Please go ahead as well on the Haiti OpenMRS config.

**Review by Ruhanga — APPROVED** [review]

**Pull request merged**
