### PR TITLE
C2C-18 Form revision - Echographie

### PR DESCRIPTION
**Pull request by mupagasi**
I have reviewed C2C 18 form -  Echographie: 
+ revised bahmniform configuration: Echographie.json file
+ revised concept configuration: Echographie.csv file

### CODE REVIEW

**Comment by mupagasi** [comment]
This  PR still have some issues to fix, kindly wait merging this

image

I'm having an issue with translation, the Init module don't import the translation, i'm reproducing and investigating what could be the problem.
After that i will show steps to reproduce this error.

**Comment by mupagasi** [comment]
The issue has been fixed after i have created this form and exported the first version of it.

**Comment by rbuisson** [comment]
> The issue has been fixed after i have created this form and exported the first version of it.
Thanks for clarifying this.
Could you however establish the steps to reproduce the error and document that as clear as possible on a GitHub issue in the Initializer repo?
https://github.com/mekomsolutions/openmrs-module-initializer/issues

**Comment by mupagasi** [comment]
The issue is logged here: https://github.com/mekomsolutions/openmrs-module-initializer/issues/75

**Pull request merged**
